# Request REST API for Student Management GET http://localhost:3000/api/v1/student/students/

###
@host = http://localhost:3000
@career_id = 3
GET http://localhost:3000/api/v1/student/students/:Id

###

POST http://localhost:3000/api/v1/student/students/ content-type: application/json {

    "Name": "pepe", "LastName": "perez", "Email": "pepePerez@gmail.com", "Dni": 34123467,

}

###

PUT http://localhost:3000/api/v1/student/students/:Id

### # Request REST API for Course Management

GET http://localhost:3000/api/v1/career/

###

GET http://localhost:3000/api/v1/career/:Id

###

POST http://localhost:3000/api/v1/Career
Content-Type: application/json

{
    "Name":"Ingeniería en Sistemas",
    "Description":"Carrera enfocada en el desarrollo de software y sistemas de información.",
    "Duration": 5,
    "Qualification": "Licenciatura",
    "HeadOfCareerId": 3
}


###

PUT http://localhost:3000/api/v1/career/:Id

### # Request REST API for Professor Management

GET http://localhost:3000/api/v1/professor/professors/

###

GET http://localhost:3000/api/v1/professor/professors/:Id

###

POST http://localhost:3000/api/v1/professor/professors/

###

PUT http://localhost:3000/api/v1/professor/professors/:Id
